### ISSUE TITLE
The run fails because packageUrlJson object is null

### ISSUE THREAD

**Issue by skarami** [advanced-security/component-detection-dependency-submission-action#80]
We are trying to use this action in our dependency submission workflow and encountered an error. Please see the following screenshot for details. 

<img width="1115" alt="Screenshot 2024-11-20 at 1 32 34 PM" src="https://github.com/user-attachments/assets/5231e8e4-60ea-432d-b0a3-e79ce50f47ea">

**Context:**
- This is a swift project
- Package manager is gem

This is the workflow that we run:
```
name: Component Detection

on:
    workflow_dispatch:
    push:
        branches: [ "main", "release/*" ]
    pull_request:
        branches: [ "main", "release/*" ]

permissions: 
  id-token: write
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
            
      - name: Component detection 
        uses: advanced-security/component-detection-dependency-submission-action@v0.0.3
```
